![Basic_Skills_Machine_Learning_006](../../images/01_Basic_Skills_Machine_Learning/006.jpg)

```python
import numpy as np

# 1: 행렬 A를 정의해보세요
A = 

# 2: 행렬 B를 정의해보세요
B = 

print(A)
print(B)
print(A[][])  # 3: 여기서 A의 2행 2열 원소에 접근해보세요
print(A[][])  # 4: 여기서 A의 4행 1열 원소에 접근해보세요
```

In [1]:
import numpy as np

# 1: 행렬 A를 정의해보세요
A = np.array([
    [0, 1, -1],
    [1, 2, 3],
    [2, 1, 0],
    [-1, 2, -4]
])

# 2: 행렬 B를 정의해보세요
B = np.array([
    [0, 2],
    [1, 1],
    [-1, -2]
])

print(A)
print(B)
print(A[1][1])  # 3: 여기서 A의 2행 2열 원소에 접근해보세요
print(A[3][0])  # 4: 여기서 A의 4행 1열 원소에 접근해보세요

[[ 0  1 -1]
 [ 1  2  3]
 [ 2  1  0]
 [-1  2 -4]]
[[ 0  2]
 [ 1  1]
 [-1 -2]]
2
-1
