In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
B

array([[0.9716558 , 0.21435979, 0.90918462],
       [0.1165928 , 0.71651197, 0.30075716],
       [0.81096928, 0.70593445, 0.47059191]])

In [ ]:
# Addition
A + B

array([[ 1.9716558 , -0.78564021,  2.90918462],
       [ 3.1165928 ,  2.71651197,  2.30075716],
       [ 4.81096928,  1.70593445,  2.47059191]])

In [6]:
# Multiply Scalar
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [ ]:
# Multiply Matrices 1
np.dot(A, B)

array([[2.47700157, 0.90971671, 1.54961129],
       [4.77009157, 3.48797221, 4.27025199],
       [5.62515458, 2.98582002, 4.87867945]])

In [ ]:
# Multiply Matrices 2
A @ B

array([[2.47700157, 0.90971671, 1.54961129],
       [4.77009157, 3.48797221, 4.27025199],
       [5.62515458, 2.98582002, 4.87867945]])

In [10]:
# Various Operation
A @ B + (A + 2 * B)

array([[ 5.42031318,  0.33843629,  5.36798052],
       [ 8.00327716,  6.92099615,  6.87176631],
       [11.24709314,  5.39768891,  7.81986328]])