In [22]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv("../data/boston.csv")
data.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9

In [3]:
data.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [5]:
X = data[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']]
y = data[['MEDV']]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [7]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 13)
(102, 13)
(404, 1)
(102, 1)


In [23]:
model = Lasso(alpha=0.1)

In [9]:
model.fit(X_train, y_train)

LinearRegression()

In [10]:
model.coef_

array([[-1.30799852e-01,  4.94030235e-02,  1.09535045e-03,
         2.70536624e+00, -1.59570504e+01,  3.41397332e+00,
         1.11887670e-03, -1.49308124e+00,  3.64422378e-01,
        -1.31718155e-02, -9.52369666e-01,  1.17492092e-02,
        -5.94076089e-01]])

In [11]:
model.intercept_

array([37.91248701])

In [12]:
y_test_prediction = model.predict(X_test)

print(y_test_prediction)

[[37.56311787]
 [32.14445143]
 [27.06573629]
 [ 5.67080633]
 [35.09982577]
 [ 5.85803701]
 [27.53708506]
 [31.81019188]
 [26.35634771]
 [22.77208748]
 [31.91183048]
 [21.50224061]
 [23.70119983]
 [33.3622504 ]
 [28.51633591]
 [14.39456899]
 [ 0.19284025]
 [18.66247155]
 [13.71004139]
 [14.13408635]
 [ 2.03263952]
 [19.7280831 ]
 [38.18657429]
 [24.19760058]
 [31.30247973]
 [11.14144544]
 [25.03636951]
 [23.27970871]
 [22.49420127]
 [20.52972594]
 [15.16513744]
 [ 6.92553586]
 [18.3557733 ]
 [22.37179804]
 [28.91287973]
 [19.02980786]
 [30.19357214]
 [ 8.74384915]
 [40.86691522]
 [34.53763591]
 [20.70224878]
 [ 2.59618963]
 [29.99590282]
 [12.15704798]
 [27.10186397]
 [30.8052437 ]
 [-6.24169079]
 [19.84885777]
 [20.92973441]
 [12.43523958]
 [20.4949947 ]
 [19.19231742]
 [23.69073157]
 [12.67998473]
 [17.14252424]
 [25.04649176]
 [34.77758126]
 [15.23294903]
 [28.22306193]
 [21.08745388]
 [20.39506129]
 [25.79476888]
 [14.72463673]
 [33.18635032]
 [23.17771307]
 [13.11057248]
 [19.23154

In [18]:
mse = mean_squared_error(y_test, y_test_prediction) ** 0.5

In [14]:
X_train

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE      DIS   RAD    TAX  \
33    1.15172   0.0   8.14   0.0  0.538  5.701   95.0   3.7872   4.0  307.0   
283   0.01501  90.0   1.21   1.0  0.401  7.923   24.8   5.8850   1.0  198.0   
418  73.53410   0.0  18.10   0.0  0.679  5.957  100.0   1.8026  24.0  666.0   
502   0.04527   0.0  11.93   0.0  0.573  6.120   76.7   2.2875   1.0  273.0   
402   9.59571   0.0  18.10   0.0  0.693  6.404  100.0   1.6390  24.0  666.0   
..        ...   ...    ...   ...    ...    ...    ...      ...   ...    ...   
486   5.69175   0.0  18.10   0.0  0.583  6.114   79.8   3.5459  24.0  666.0   
189   0.08370  45.0   3.44   0.0  0.437  7.185   38.9   4.5667   5.0  398.0   
495   0.17899   0.0   9.69   0.0  0.585  5.670   28.8   2.7986   6.0  391.0   
206   0.22969   0.0  10.59   0.0  0.489  6.326   52.5   4.3549   4.0  277.0   
355   0.10659  80.0   1.91   0.0  0.413  5.936   19.5  10.5857   4.0  334.0   

     PTRATIO       B  LSTAT  
33      21.0  358.77  18.35  
283     13.6  395.52   3.16  
418     20.2   16.45  20.62  
502     21.0  396.90   9.08  
402     20.2  376.11  20.31  
..       ...     ...    ...  
486     20.2  392.68  14.98  
189     15.2  396.90   5.39  
495     19.2  393.29  17.60  
206     18.6  394.87  10.97  
355     22.0  376.04   5.57  

[404 rows x 13 columns]

In [15]:
X_test

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
226   0.38214   0.0   6.20   0.0  0.504  8.040   86.5  3.2157   8.0  307.0   
292   0.03615  80.0   4.95   0.0  0.411  6.630   23.4  5.1167   4.0  245.0   
90    0.04684   0.0   3.41   0.0  0.489  6.417   66.1  3.0923   2.0  270.0   
373  11.10810   0.0  18.10   0.0  0.668  4.906  100.0  1.1742  24.0  666.0   
273   0.22188  20.0   6.96   1.0  0.464  7.691   51.8  4.3665   3.0  223.0   
..        ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
349   0.02899  40.0   1.25   0.0  0.429  6.939   34.5  8.7921   1.0  335.0   
212   0.21719   0.0  10.59   1.0  0.489  5.807   53.8  3.6526   4.0  277.0   
156   2.44668   0.0  19.58   0.0  0.871  5.272   94.0  1.7364   5.0  403.0   
480   5.82401   0.0  18.10   0.0  0.532  6.242   64.7  3.4242  24.0  666.0   
248   0.16439  22.0   5.86   0.0  0.431  6.433   49.1  7.8265   7.0  330.0   

     PTRATIO       B  LSTAT  
226     17.4  387.38   3.13  
292     19.2  396.90   4.70  
90      17.8  392.18   8.81  
373     20.2  396.90  34.77  
273     18.6  390.77   6.58  
..       ...     ...    ...  
349     19.7  389.85   5.89  
212     18.6  390.94  16.03  
156     14.7   88.63  16.14  
480     20.2  396.90  10.74  
248     19.1  374.71   9.52  

[102 rows x 13 columns]

In [19]:
r2 = r2_score(y_test, y_test_prediction)

print(f"MSE: {mse}, R² Score: {r2}")

MSE: 4.568292042303157, R² Score: 0.7334492147453135


In [24]:
params = {'alpha': [0.1, 1.0, 10]}  # 하이퍼파라미터 후보
grid = GridSearchCV(model, param_grid=params, cv=5)
grid.fit(X_train, y_train)

print("최적 파라미터:", grid.best_params_)

최적 파라미터: {'alpha': 0.1}
