In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [10]:
data = pd.read_csv("../data/boston.csv")
data.tail()

CRIM   ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
501  0.06263  0.0  11.93   0.0  0.573  ...  273.0     21.0  391.99   9.67  22.4
502  0.04527  0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   9.08  20.6
503  0.06076  0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   5.64  23.9
504  0.10959  0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48  22.0
505  0.04741  0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88  11.9

[5 rows x 14 columns]

In [17]:
x = data[['AGE']]

In [18]:
y = data[['MEDV']]

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

In [22]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(404, 1)
(102, 1)
(404, 1)
(102, 1)


In [24]:
model = LinearRegression()

In [25]:
model.fit(x_train, y_train)

LinearRegression()

In [26]:
model.coef_

array([[-0.12402883]])

In [27]:
model.intercept_

array([31.04617413])

In [28]:
# 최적선: f(x) = 31.04617413 -0.12402883x

In [29]:
y_test_prediction = model.predict(x_test)
y_test_prediction

array([[20.31768041],
       [28.14389953],
       [22.84786852],
       [18.64329122],
       [24.62148078],
       [19.99520545],
       [19.75955068],
       [22.79825699],
       [20.92542167],
       [21.74401194],
       [23.29437231],
       [25.41526529],
       [21.53316293],
       [25.94858925],
       [23.76568186],
       [24.55946636],
       [18.64329122],
       [18.64329122],
       [22.00447248],
       [18.64329122],
       [18.89134887],
       [18.90375176],
       [21.33471681],
       [22.71143681],
       [28.46637448],
       [19.06498923],
       [24.31140871],
       [22.05408402],
       [26.32067574],
       [26.59353916],
       [19.0153777 ],
       [18.85414022],
       [19.30064401],
       [18.7301114 ],
       [28.76404367],
       [18.92855752],
       [21.5579687 ],
       [19.21382383],
       [19.69753626],
       [29.08651863],
       [19.56110455],
       [18.64329122],
       [21.02464473],
       [20.14404005],
       [24.72070384],
       [25

In [32]:
mean_squared_error(y_test, y_test_prediction) ** 0.5

8.236881612652454

In [34]:
x = data[['CRIM']]
y = data[['MEDV']]

model = LinearRegression()

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

 model.fit(x_train, y_train)

y_test_prediction = model.predict(x_test)


mean_squared_error(y_test, y_test_prediction) ** 0.5

8.180697228317348

In [36]:
model = LinearRegression()

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=5)

model.fit(X_train, y_train)

y_test_predict = model.predict(X_test)
# 테스트 코드 (평균 제곱근 오차로 모델 성능 평가)
mse = mean_squared_error(y_test, y_test_predict)

mse ** 0.5

8.180697228317348