In [1]:
import numpy as np

In [2]:
a = np.arange(6, 10)
a

array([6, 7, 8, 9])

In [3]:
b = np.arange(10, 14)
b

array([10, 11, 12, 13])

In [4]:
c = a * b
c

array([ 60,  77,  96, 117])

In [5]:
d = a[:, np.newaxis]
d

array([[6],
       [7],
       [8],
       [9]])

In [7]:
e = b[np.newaxis, :]
e

array([[10, 11, 12, 13]])

In [8]:
e.shape

(1, 4)

In [12]:
print(d, e)

[[6]
 [7]
 [8]
 [9]] [[10 11 12 13]]


In [13]:
f = d@e
f

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [15]:
d.dot(e)

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [16]:
a2 = np.array([1, 2, 3, 4])
a2

array([1, 2, 3, 4])

In [17]:
a2 = a2.reshape(2, 2)
a2

array([[1, 2],
       [3, 4]])

In [18]:
np.sum(a2)

10

In [19]:
np.sum(a2, axis=0)

array([4, 6])

In [20]:
np.sum(a2, axis=1)

array([3, 7])

In [21]:
a3 = np.arange(1, 9)
a3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a3 = a3.reshape(2, 2, 2)
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
a3.shape

(2, 2, 2)

In [24]:
a3[0]

array([[1, 2],
       [3, 4]])

In [25]:
a3[0, 0]

array([1, 2])

In [26]:
a3[0, 0, 0]

1

In [28]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
print(np.sum(a3, axis=0))
print(np.sum(a3, axis=1))
print(np.sum(a3, axis=2))

[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


In [29]:
np.sum(a3)

36

In [31]:
a = np.array([4, 5])
b = np.array([3, 4, 6])

print(a.shape, b.shape)

(2,) (3,)


In [32]:
try:
    a + b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [33]:
a = np.append(a, [6])
a.shape

(3,)

In [34]:
a + b

array([ 7,  9, 12])

In [36]:
a2 = np.array([[1, 2, 3], [3, 4, 5,]])
b2 = np.array([1, 2])

In [37]:
b2 = np.append(b2, [3])
a2 + b2

array([[2, 4, 6],
       [4, 6, 8]])

In [38]:
a2.shape

(2, 3)